import { APP_VERSION } from '../../../constants/meta';
import path from 'path';

export default function assTemplate(fileName, comments = {}) {
  return `[Script Info]
; Script generated by Aegisub r8942
; http://www.aegisub.org/
Title: ${path.basename(fileName, path.extname(fileName))}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1440
BangDreamTranslatorTools: ${APP_VERSION}
${Object.keys(comments)
    .map(key => `${key}: ${JSON.stringify(comments[key])}`)
    .join('\n')}

[Aegisub Project Garbage]
Audio File: ${path.basename(fileName)}
Video File: ${path.basename(fileName)}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Credit,Layiji MaHaNiYom V1.61,80,&H00EEDDFF,&H0006067E,&H007733FF,&H00000000,-1,-1,0,0,100,100,0,0,1,12,2,9,0,70,20,1
Style: Text,Layiji MaHaNiYom V1.61,66,&H00545154,&H00FFFFFF,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1
Style: Text - Rectangle,Layiji MaHaNiYom V1.61,66,&H00545154,&H00FFFFFF,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1
Style: Text - Cloud,Layiji MaHaNiYom V1.61,60,&H00545154,&H00FFFFFF,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1
Style: Text - Shout,Layiji MaHaNiYom V1.61,72,&H00545154,&H00FFFFFF,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:00.00,Default,▼CODE LINES▼,0,0,0,,
Comment: 0,0:00:00.00,0:00:00.00,Credit,,0,0,0,template notext line,!retime("line", 0, 0)!{\\p1\\fad(1000,1000)\\blur0\\1c&H7733FF&\\3c&HEEDDFF&\\fscx35\\fscy35\\bord5\\pos(1885,90)}m 121 7 b 104 -29 98 -29 81 7 b 46 12 49 27 71 43 b 61 81 72 89 101 68 b 129 91 144 80 131 43 b 156 21 154 10 121 7 m 173 -112 l 98 -32 b 99 -26 108 -23 113 -21 l 186 -97 b 190 -104 184 -115 173 -112 m 175 -81 b 187 -87 193 -70 188 -65 l 124 -2 b 122 -7 119 -11 115 -17 m 177 -50 b 186 -50 192 -44 189 -34 l 149 7 b 146 6 137 1 130 0 m 185 2 b 192 -9 187 -20 174 -14 l 153 9 l 151 10 b 159 21 152 28 150 35 m 140 55 l 140 75 b 142 80 144 80 147 77 l 189 30 b 190 19 186 15 174 17
Comment: 0,0:00:00.00,0:00:00.00,Credit,,0,0,0,template line,!retime("line", 0, 0)!{\\fad(1000,1000)\\blur5\\3a&H20&}
Comment: 0,0:00:00.00,0:00:00.00,Text,,0,0,0,code once,db = {}; margin = 10
Comment: 0,0:00:00.00,0:00:00.00,Text,,0,0,0,code line,_, _,actorX,fontX = string.find(line.actor, "([%d.]*)%p*([%d.]*)"); actor = _G.tonumber(actorX); if fontX=="" then fontSize = 66 else fontSize = _G.tonumber(fontX) end;
Comment: 0,0:00:00.00,0:00:00.00,Text,,0,0,0,template noblank notext line,!retime('set',db[actor][j].t,db[actor][j+1].t)!!maxloop(#db[actor]-1)!{\\p1\\an5\\bord0\\shad0\\c&HFBF9F9&\\clip(!db[actor][j].x-margin-db[actor][j].w/2!,!db[actor][j].y-margin-db[actor][j].h/2!,!db[actor][j].x+margin+db[actor][j].w/2!,!db[actor][j].y+margin+db[actor][j].h/2!)\\t(0,!db[actor][j+1].t-db[actor][j].t!,\\clip(!db[actor][j+1].x-margin-db[actor][j+1].w/2!,!db[actor][j+1].y-margin-db[actor][j+1].h/2!,!db[actor][j+1].x+margin+db[actor][j+1].w/2!,!db[actor][j+1].y+margin+db[actor][j+1].h/2!))}m 0 0 l 1920 0 l 1920 1440 l 0 1440
Comment: 0,0:00:00.00,0:00:00.00,Text,,0,0,0,template noblank line,!retime('set',db[actor][j].t,db[actor][j+1].t)!!maxloop(#db[actor]-1)!{\\an5\\fs!fontSize!\\fscx!db[actor][j].p!\\fscy!db[actor][j].p!\\t(0,!db[actor][j+1].t-db[actor][j].t!,\\fscx!db[actor][j+1].p!\\fscy!db[actor][j+1].p!)\\move(!db[actor][j].x!,!db[actor][j].y!,!db[actor][j+1].x!,!db[actor][j+1].y!,0,!db[actor][j+1].t-db[actor][j].t!)}
Comment: 0,0:00:00.00,0:00:00.00,Text - Rectangle,,0,0,0,code line,_, _,x1,y1,x2,y2,size = string.find(line.actor, "([%d.]*)%p*([%d.]*)%p*([%d.]*)%p*([%d.]*)%p*([%d.]*)"); if size=="" then size = 66 end; xcen = (x1+x2)/2; ycen = (y1+y2)/2; 
Comment: 0,0:00:00.00,0:00:00.00,Text - Rectangle,,0,0,0,code line,margin = 15; textMargin = 3; offSetY=110; y0 = y2+45; ytext=ycen+textMargin; ytext0=ytext+offSetY; x1=x1+margin; y1=y1+margin; x2=x2-margin; y2=y2-margin;
Comment: 0,0:00:00.00,0:00:00.00,Text - Rectangle,,0,0,0,template noblank notext line,!retime('line',-150,200)!{\\p1\\an5\\bord0\\shad0\\c&f9f9fb&\\clip(!xcen!,!y0!,!xcen!,!y0!)\\t(16.66,166.66,\\clip(!x1!,!y1!,!x2!,!y2!))\\t(!$ldur+140!,!$ldur+340!,\\clip(!xcen!,!y0!,!xcen!,!y0!))}m 0 0 l 1920 0 l 1920 1440 l 0 1440
Comment: 0,0:00:00.00,0:00:00.00,Text - Rectangle,,0,0,0,template noblank line,!retime('preline',-150,50)!{\\an5\\fscx0\\fscy0\\t(16.66,166.66,\\fscx100\\fscy100)\\move(!xcen!,!ytext0!,!xcen!,!ytext!,16.66,166.66)\\fs!size!}
Comment: 0,0:00:00.00,0:00:00.00,Text - Rectangle,,0,0,0,template noblank line,!retime('line',50,200)!{\\an5\\fscx100\\fscy100\\t(!$ldur-60!,!$ldur+140!,\\fscx0\\fscy0)\\move(!xcen!,!ytext!,!xcen!,!ytext0!,!$ldur-60!,!$ldur+140!)\\fs!size!}
Comment: 0,0:00:00.00,0:00:00.00,Text - Shout,,0,0,0,code once,time = {20,80,100,140,150}; progress = {0,1.1,0.965,1.09,1}; offsetY = {80,-7.5,0,-7.5,0}
Comment: 0,0:00:00.00,0:00:00.00,Text - Shout,,0,0,0,code line,_, _,x1,y1,x2,y2,size = string.find(line.actor, "([%d.]*)%p*([%d.]*)%p*([%d.]*)%p*([%d.]*)%p*([%d.]*)"); if size=="" then size = 72 end; xcen = (x1+x2)/2; ycen = (y1+y2)/2;
Comment: 0,0:00:00.00,0:00:00.00,Text - Shout,,0,0,0,code line,margin = 15; textMargin = 3; endX=25; endY=10; offSetY=90; x0 = endX/2; y0 = ycen+offSetY; ytext=ycen+textMargin; ytext0=ytext+offSetY; x1=x1+margin; y1=y1+margin; x2=x2-margin; y2=y2-margin; xhalf = (x2-x1)/2; yhalf = (y2-y1)/2
Comment: 0,0:00:00.00,0:00:00.00,Text - Shout,,0,0,0,code line,function genClip()  local out = "";  for i=1,4 do  out = out.."\\\\t("..time[i]..","..time[i+1]..",\\\\clip("..xcen-xhalf*progress[i+1]..","..ycen-yhalf*progress[i+1]..","..xcen+xhalf*progress[i+1]..","..ycen+yhalf*progress[i+1].."))" end  return out;end
Comment: 0,0:00:00.00,0:00:00.00,Text - Shout,,0,0,0,template noblank notext line,!retime('line',-133.33,200)!{\\p1\\an5\\bord0\\shad0\\c&HFBF9F9&\\clip(!xcen!)\\t(!$ldur+133.33!,!$ldur+333.33!,\\clip(!xcen!,!y0!,!xcen!,!y0!))}m 0 0 l 1920 0 l 1920 1440 l 0 1440
Comment: 0,0:00:00.00,0:00:00.00,Text - Shout,,0,0,0,template noblank line loop 4,!retime('preline',-133.33+time[j],-133.33+time[j+1])!{\\an5\\fscx!progress[j]*100!\\fscy!progress[j]*100!\\t(time[j],time[j+1],\\fscx!progress[j+1]*100!\\fscy!progress[j+1]*100!)\\move(!xcen!,!ytext+offsetY[j]!,!xcen!,!ytext+offsetY[j+1]!,time[j],time[j+1])\\fs!size!}
Comment: 0,0:00:00.00,0:00:00.00,Text - Shout,,0,0,0,template line,!retime('line',0,200)!{\\an5\\fscx100\\fscy100\\t(!$ldur!,!$ldur+200!,\\fscx0\\fscy0)\\move(!xcen!,!ytext!,!xcen!,!ytext0!,!$ldur!,!$ldur+200!)\\fs!size!}
Comment: 0,0:00:00.00,0:00:00.00,Text - Cloud,,0,0,0,code line,_, _,x1,y1,x2,y2,size = string.find(line.actor, "([%d.]*)%p*([%d.]*)%p*([%d.]*)%p*([%d.]*)%p*([%d.]*)"); if size=="" then size = 60 end; xcen = (x1+x2)/2; ycen = (y1+y2)/2;
Comment: 0,0:00:00.00,0:00:00.00,Text - Cloud,,0,0,0,code line,margin = 0; textMargin = 0; y0 = y2+45; ytext=ycen+textMargin; ytext0=ytext+117; x1=x1+margin; y1=y1+margin; x2=x2-margin; y2=y2-margin;
Comment: 0,0:00:00.00,0:00:00.00,Text - Cloud,,0,0,0,template noblank notext line,!retime('line',-150,200)!{\\p1\\an5\\bord0\\shad0\\c&HFBF9F9&\\clip(!xcen!,!y0!,!xcen!,!y0!)\\t(16.66,166.66,\\clip(!x1!,!y1!,!x2!,!y2!))\\t(!$ldur+140!,!$ldur+340!,\\clip(!xcen!,!y0!,!xcen!,!y0!))}m 0 0 l 1920 0 l 1920 1440 l 0 1440
Comment: 0,0:00:00.00,0:00:00.00,Text - Cloud,,0,0,0,template noblank line,!retime('preline',-150,50)!{\\an5\\fscx0\\fscy0\\t(16.66,166.66,\\fscx100\\fscy100)\\move(!xcen!,!ytext0!,!xcen!,!ytext!,16.66,166.66)\\fs!size!}
Comment: 0,0:00:00.00,0:00:00.00,Text - Cloud,,0,0,0,template noblank line,!retime('line',50,200)!{\\an5\\fscx100\\fscy100\\t(!$ldur-60!,!$ldur+140!,\\fscx0\\fscy0)\\move(!xcen!,!ytext!,!xcen!,!ytext0!,!$ldur-60!,!$ldur+140!)\\fs!size!}
`;
}
